import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import AuthProvider from '@/context-providers/AuthProvider'
import CategoriesProvider from '../context-providers/CategoriesProvider'
import RecordsProvider from '@/context-providers/RecordsProvider'
import ReportsProvider from '@/context-providers/ReportsProvider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <CategoriesProvider>
            <RecordsProvider>
              <ReportsProvider>
                <>
                  {children}
                </>
              </ReportsProvider>
            </RecordsProvider>
          </CategoriesProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
